import cv2 as cv

# This file reads the QR code generated by qr_code_generator.py and prints out the data in the terminal

path = r'D:\xampp\htdocs\hub-portal\QR Reader script\QR_code.png'

img = cv.imread(path, 0) #image is now loaded in OpenCV; 0 is a flag - image will be loaded in black and white
detection = cv.QRCodeDetector()

#    detect — Detects QR code in image and returns the quadrangle containing the code.
#    decode — Decodes QR code in the image once it’s found by the detect() method.
#       Returns UTF8-encoded output string or an empty string if the code cannot be decoded.
#    detectAndDecode — Both detect and decode QR code.

retval, points, straight_qrcode = detection.detectAndDecode(img)
print('INFO: ', retval, "\n" "\n" 'POINTS: ', points, "\n" 'QR CODE MATRIX: ' "\n" ,straight_qrcode)

    #retval — Result in a string.
    #points — Array of vertices of the found QR code quadrangle. Will be empty if not found.
    #straight_qrcode — An image containing rectified and binarized QR code.

cv.imshow('image',img)
cv.waitKey(0)
